get_rinfo <- function(data = c("inputDB", "Output_5", "Output_10",
                               "qualityMetrics")) {
        # osf id (for osfr), column classes, and skip lines
        rinfo <- switch(data[1],
                        inputDB        = list("9dsfk",
                                              c("character","character",
                                                "character","character",
                                                "character","character",
                                                "integer",  "character",
                                                "character","numeric",
                                                "character"),
                                              1),
                        Output_5       = list("7tnfh",
                                              c("character","character",
                                                "character","character",
                                                "character","integer",
                                                "integer",  "numeric",
                                                "numeric",  "numeric"),
                                              3),
                        Output_10      = list("43ucn",
                                              c("character","character",
                                                "character","character",
                                                "character","integer",
                                                "integer",  "numeric",
                                                "numeric",  "numeric"),
                                              3),
                        qualityMetrics = list("qpfw5",
                                              c("character","character",
                                                "Date",     "character",
                                                "numeric",  "numeric",
                                                "numeric",  "character",
                                                "character","integer",
                                                "integer",  "integer",
                                                "integer",  "integer",
                                                "integer",  "logical",
                                                "numeric",  "numeric"),
                                              1))

        return (rinfo)
}
